cmake_minimum_required(VERSION 3.11)

# Configure Assimp options before adding subdirectory
set(ASSIMP_BUILD_TESTS OFF CACHE BOOL "" FORCE)
set(ASSIMP_BUILD_ASSIMP_TOOLS OFF CACHE BOOL "" FORCE)
set(ASSIMP_INSTALL OFF CACHE BOOL "" FORCE)
set(ASSIMP_BUILD_ALL_IMPORTERS_BY_DEFAULT OFF CACHE BOOL "" FORCE)
set(ASSIMP_BUILD_OBJ_IMPORTER ON CACHE BOOL "" FORCE)
set(ASSIMP_BUILD_FBX_IMPORTER ON CACHE BOOL "" FORCE)
set(ASSIMP_BUILD_GLTF_IMPORTER ON CACHE BOOL "" FORCE)
set(ASSIMP_BUILD_PLY_IMPORTER ON CACHE BOOL "" FORCE)

# Ensure Assimp respects the build type for optimizations
set(ASSIMP_BUILD_SHARED_LIBS OFF CACHE BOOL "" FORCE)

# Add assimp subdirectory (assimp is in SOGLR/assimp/)
add_subdirectory(${CMAKE_CURRENT_SOURCE_DIR}/assimp ${CMAKE_CURRENT_BINARY_DIR}/assimp)